### ISSUE TITLE
don't poke the tiger

### ISSUE THREAD

**Issue by vinbarnes** [websages/nashville#1]
I repeat, don't poke the tiger.

**Comment by rick** [comment]
![](http://orig05.deviantart.net/4402/f/2012/099/f/a/tiger_loves_a_wolf_by_poke_freak123-d4vljy1.jpg)

**Comment by azizshamim** [comment]
👉 🐅

**Comment by azizshamim** [comment]
or is it 🐅 👈 ? I can't tell.

**Comment by vinbarnes** [comment]
🐯
👆
